### ISSUE TITLE
Bug in events.

### ISSUE THREAD

**Issue by nicola-spb** [thednp/bootstrap.native#251] opened 2018-10-31 17:25 UTC
When every component (Tooltip, Popover, Modal etc) was created some times handlers will be from first component. It`s incorrect and will have memory leak because handlers will have link on other (first) component.

Example:
```
var modal = new Modal(el, options1);
modal = new Modal(el, options2);
```

Is it bug?

```
if ( !(stringAffix in element ) ) { // prevent adding event handlers twice
      on( globalObject, scrollEvent, self[update] );
      !isIE8 && on( globalObject, resizeEvent, self[update] );
}
```
```

if ( !(stringAlert in element ) ) { // prevent adding event handlers twice
      on(element, clickEvent, clickHandler);
}
```

```
if ( !( stringButton in element ) ) { // prevent adding event handlers twice
        on( element, clickEvent, toggle );
        queryElement('['+tabindex+']',element) && on( element, keyupEvent, keyHandler ), 
                                                  on( element, keydownEvent, preventScroll );
}
```
etc

**Comment by thednp** [comment] 2018-10-31 18:04
Well to me it makes no sense to initialize same component for same element twice, but I understand what you're trying to say, might be a memory leak although I never had any issues with the versions 2.0.0 and above.

Lately I was working on ways to export handlers to global objects' events (DOCUMENT, WINDOW) and I think I have a good idea on how to improve future versions, it's gonna require a lot of effort to change all that.

**Comment by nicola-spb** [comment] 2018-10-31 18:20
User can initialize it twice: one by default and write some code for initialization.

**Comment by thednp** [comment] 2018-11-03 09:40
How about this:

```js
// options
var options1 = {
  interval: 5500,
  pause: 'hover'
};

var options2 = {
  interval: false,
  pause: false
};

// init
var myCarouselInit = new Carousel ('#myCarousel', options1);

// change options
myCarouselInit.interval = options2.interval;
myCarouselInit.pause = options2.pause;
```

Now the only issue with this particular component is when the change involves changing the content by adding/removing new/existing content items, a case where I would do something like this:

```js
// init
var myCarouselInit = new Carousel ('#myCarousel', options1);

// change occurs
var myCarousel = document.getElementById('myCarousel');
// remove second content item
myCarousel.removeChild(myCarousel.querySelectorAll('.item')[1]);
// remove second content item's navigation
myCarousel.removeChild(myCarousel.querySelectorAll('[data-slide-to]')[1]);

// "destroy" the initial init
myCarousel.Carousel = null; // we keep this so we don't re-add events
myCarouselInit = null;

// re-init with new options and contents
 var myCarouselInit2 = new Carousel ('#myCarousel', options2);
```

What do you think, will you give this a try?

**Comment by nicola-spb** [comment] 2018-11-05 11:40
I know that user can change some properties but he need read source for it.
If you change logic of your bootstrap component then user must be change his source. 
My opinion: user should use your components like black box with public methods without read source and searching events and changeable properties.

**Comment by thednp** [comment] 2018-11-05 12:10
IMO: you like the script, you read docs and start implementing it. That's what Bootstrap original plugin developers expect from you too, not just me.

I never heard someone complain the events of our components are incorrect when it comes to init + change/destroy + re-init, mostly later added elements, but if someone comes with a good argument, I will have no problem taking the time to try to improve the components.

As a matter of fact, I've considered making a `destroy()` method either for global use or component specific, but this was a practice mostly for legacy browsers, so since now modern browsers have some very smart garbage collection and memory cleanup capability (I've done extensive research on the matter for my KUTE.js library), I decided not to implement them.

Once you remove an element from the document, all associated events and objects/instances are garbage collected, so the use of a `destroy()` method is really not needed anymore.

I will close this for now, I believe my arguments are on everyone else's mind.

**Closed by thednp** 2018-11-05 12:10 UTC
Labels: community question, help wanted

**Comment by midzer** [comment] 2018-11-17 16:47
I can confirm v4 Carousel leaks memory (checking with Chromium Task Manager)

**Comment by thednp** [comment] 2018-11-18 05:00
We're open to any suggestions on how to improve the code.

**Comment by thednp** [comment] 2020-01-03 07:21
@nicola-spb please have a test at the master, enjoy :)
